import { activeFindings, groupByRule } from "../score.js";
import { pluralize } from "../util.js";

/**
 * The agent-executable deliverable.
 *
 * This file is written to be pasted into a coding agent and worked top to bottom. Two
 * design choices follow from that: every task carries its own acceptance criteria, so
 * the agent can tell when it is done without asking; and the protocol explicitly forbids
 * the shortcuts an agent reaches for under pressure — suppression comments, blanket
 * refactors, and marking a task done because the pattern stopped matching.
 */
export function renderFixPlan(result, meta) {
  const { summary, project, stats, ai } = result;
  const active = activeFindings(result.findings);
  const groups = groupByRule(active);
  const out = [];

  out.push(`# Fix plan — ${project.name}`);
  out.push("");
  out.push(`Generated by Tripwire ${meta.version} on ${meta.scannedAt}. Baseline score **${summary.score}/100 (${summary.grade})** across ${stats.files} ${pluralize(stats.files, "file")}.`);
  out.push("");
  out.push(`${active.length} ${pluralize(active.length, "task")}: ${summary.bySeverity.critical} critical, ${summary.bySeverity.high} high, ${summary.bySeverity.medium} medium, ${summary.bySeverity.low} low.`);
  out.push("");

  if (!active.length) {
    out.push("Nothing to fix — the scan found no active findings. Re-run Tripwire after your next substantial change.");
    out.push("");
    return `${out.join("\n")}\n`;
  }

  out.push(`## How to work this plan`);
  out.push("");
  out.push(`You are fixing real findings in a real codebase. Work one task at a time, in the order listed — they are sorted by severity, and the critical ones are the reason this file exists.`);
  out.push("");
  out.push(`For each task:`);
  out.push("");
  out.push(`1. **Read the code first.** Open the file at the cited line and read enough of the surrounding function to understand what the value is and where it comes from. The finding tells you what pattern matched; only the code tells you whether it matters here.`);
  out.push(`2. **Decide whether it is real.** If the surrounding code already handles the concern — the value is parameterized, validated, constant, or unreachable from outside — mark the task \`[~]\` and write one sentence saying what mitigates it. That is a complete, correct outcome, not a failure.`);
  out.push(`3. **Fix it properly if it is real.** Apply the remediation described in the task. Match the conventions of the surrounding code.`);
  out.push(`4. **Check the acceptance criteria.** They are written to be verifiable by reading the changed code. Do not mark a task done until they hold.`);
  out.push(`5. **Mark the checkbox and move on.** \`[x]\` fixed, \`[~]\` not applicable with a reason, \`[!]\` blocked with a reason.`);
  out.push("");
  out.push(`Rules for the whole plan:`);
  out.push("");
  out.push(`- **Never suppress instead of fixing.** Do not add ignore comments, disable rules, rename variables to dodge the pattern, or move code to a file the scanner skips. If a finding is wrong, mark it \`[~]\` and explain why.`);
  out.push(`- **Keep each change scoped to its task.** Do not refactor surrounding code, reformat files, upgrade dependencies, or fix findings from other tasks along the way. Small, reviewable diffs.`);
  out.push(`- **Rotate before you remove.** For any committed credential, the secret must be treated as compromised. Deleting the line does not fix it — the value stays valid and stays in git history. Rotation is a human action; flag it and stop.`);
  out.push(`- **Run the tests after each task** if the project has them. A fix that breaks the suite is not a fix.`);
  out.push(`- **Report honestly at the end.** State how many tasks you fixed, how many you marked not applicable and why, and anything you could not resolve. Do not claim completion for work you did not verify.`);
  out.push("");

  if (result.engines?.coverage?.some((entry) => entry.ran)) {
    const ran = result.engines.coverage.filter((entry) => entry.ran).map((entry) => entry.label);
    out.push(`> **Some tasks came from other engines** (${ran.join(", ")}). Those carry a **Reported by** line naming the engine and its rule id — go read that rule before deciding a finding is wrong. Tripwire normalized the severity and confidence; it did not re-derive the finding.`);
    out.push("");
  }

  if (!ai?.used) {
    out.push(`> **These findings were not triaged by a model.** Each one is a pattern match with a stated confidence. Tasks marked *unverified* are the most likely to be false positives — read those especially carefully before changing anything.`);
    out.push("");
  }

  out.push(`## Verification`);
  out.push("");
  out.push(`After finishing a batch of tasks, re-run the scan and confirm the score moved and the fixed rules are gone:`);
  out.push("");
  out.push("```sh");
  out.push(`npx @lapointelabs/tripwire scan ${project.relative === "." ? "." : project.relative}`);
  out.push("```");
  out.push("");
  if (meta.verifyCommands?.length) {
    out.push(`This project also defines:`);
    out.push("");
    out.push("```sh");
    for (const command of meta.verifyCommands) out.push(command);
    out.push("```");
    out.push("");
  }

  out.push(`## Tasks`);
  out.push("");

  let index = 0;
  for (const group of groups) {
    for (const finding of group.findings) {
      index += 1;
      out.push(...renderTask(index, finding, group));
    }
  }

  out.push(`## Progress`);
  out.push("");
  out.push(`| Total | Fixed | Not applicable | Blocked |`);
  out.push(`| ---: | ---: | ---: | ---: |`);
  out.push(`| ${active.length} | | | |`);
  out.push("");
  out.push(`Fill this in as you go, and re-run the scan to confirm the new score.`);
  out.push("");

  return `${out.join("\n")}\n`;
}

function renderTask(number, finding, group) {
  const out = [];
  const label = `${finding.severity.toUpperCase()} · ${finding.ruleId}`;
  out.push(`### ${number}. [ ] ${group.title} — \`${finding.file}:${finding.line}\``);
  out.push("");
  out.push(`> ${label} · ${confidenceNote(finding)}`);
  out.push("");
  out.push(`**What matched.** ${finding.message}`);
  out.push("");
  if (finding.source) {
    // Name the engine and its rule. An agent deciding whether a finding is real needs
    // somewhere to go and read the rule's own definition; "the scanner said so" is not it.
    const agreement = finding.corroboratedBy?.length ? ` Independently confirmed by ${finding.corroboratedBy.join(", ")}.` : "";
    const refs = finding.source.refs?.length ? ` Reference: ${finding.source.refs[0]}` : "";
    out.push(`**Reported by.** ${finding.source.label}, rule \`${finding.source.ruleId}\`.${agreement}${refs}`);
    out.push("");
  } else if (finding.corroboratedBy?.length) {
    out.push(`**Reported by.** Tripwire, independently confirmed by ${finding.corroboratedBy.join(", ")}.`);
    out.push("");
  }
  if (finding.evidence) {
    out.push("```");
    out.push(`${finding.file}:${finding.line}`);
    out.push(finding.evidence);
    out.push("```");
    out.push("");
  }
  out.push(`**Why it matters.** ${group.why}`);
  out.push("");
  out.push(`**What to do.** ${finding.verdict?.fix || group.fix}`);
  out.push("");
  if (finding.verdict?.reason) {
    out.push(`**Triage note.** ${finding.verdict.reason}`);
    out.push("");
  }
  out.push(`**Done when:**`);
  out.push("");
  for (const criterion of acceptanceCriteria(finding, group)) out.push(`- [ ] ${criterion}`);
  out.push("");
  return out;
}

function confidenceNote(finding) {
  if (finding.verdict?.real === true) return `confirmed by triage (${finding.verdict.confidence} confidence)`;
  return {
    high: "high confidence — the pattern is unambiguous",
    medium: "likely — read the surrounding code before changing it",
    low: "unverified — most likely to be a false positive"
  }[finding.confidence] || finding.confidence;
}

/**
 * Per-rule acceptance criteria. These are the difference between a plan an agent can
 * close out honestly and one where "the pattern no longer matches" counts as done.
 */
export function acceptanceCriteria(finding, group) {
  const location = `\`${finding.file}\``;
  const generic = [
    `The concern described above no longer applies at ${location}, and you can say in one sentence why.`,
    `No ignore comment, rule disable, or scanner-dodging rename was used.`,
    `Existing tests still pass (or the project has none).`
  ];

  const byRule = {
    "injection/sql-interpolation": [
      `Every value that varies at runtime reaches the query as a bound parameter, not as text spliced into the SQL string.`,
      `Any genuinely dynamic identifier (table or column name) is validated against a hard-coded allow-list before use.`,
      `The query still returns the same results for a normal input — verify with an existing test or a manual call.`
    ],
    "injection/command-execution": [
      `The command is invoked with an argument array (\`execFile\`, \`spawn\` without \`shell: true\`, \`subprocess.run([...])\`, \`ArgumentList\`) so no shell parses the arguments.`,
      `No user-influenced value is concatenated into a command string anywhere on this path.`
    ],
    "injection/dynamic-code-execution": [
      `The dynamic evaluation is gone, replaced by an explicit dispatch table, a parser, or \`JSON.parse\` — or, if it must stay, its input is restricted to a hard-coded allow-list checked immediately before evaluation.`
    ],
    "injection/path-traversal": [
      `The joined path is resolved and then checked to still sit inside the intended root before any filesystem call.`,
      `A path that escapes the root is rejected with an error, not silently clamped or normalized into range.`
    ],
    "secrets/committed-credential": [
      `**The credential has been rotated.** This is not optional and cannot be done by editing files — the old value stays valid until someone revokes it. If you cannot rotate it, mark this task \`[!]\` and say so plainly.`,
      `The literal value is gone from the working tree and loaded from the environment or a secret manager instead.`,
      `The file holding it is covered by \`.gitignore\` if it is a local config file.`
    ],
    "external/secret": [
      `**The credential has been rotated.** A secret-scanning engine found it, which means the value is in a file anyone with repository access can read — and, if it was ever pushed, in history where deleting the line does not reach it. Where the finding says *verified*, the engine authenticated with the key successfully: there is nothing left to assess. Rotation is a human action; if you cannot do it, mark this \`[!]\` and say so.`,
      `The literal value is gone from the working tree and loaded from the environment or a secret manager instead.`,
      `You have checked whether the same value appears elsewhere in the repository — credentials are usually copied, not moved.`
    ],
    "external/agent-surface": [
      `The component's own description text has been read in full, not just its name — the payload, if there is one, is in the prose the model receives.`,
      `Anything instructing the model to ignore prior context, read credentials or environment variables, or contact an unrelated host is removed, and the component is removed with it if that was its purpose.`,
      `The component is pinned to a version and a source you control, so its instructions cannot change without a change landing in this repository.`
    ],
    "external/code-analysis": [
      `You have read the engine's own rule text for the id cited above and followed the path it reports from entry point to sink.`,
      `The fix is at the sink and uses a construct that cannot express the unsafe form, rather than a validation bolted on upstream that a future caller can bypass.`
    ],
    "external/agent-config": [
      `The defect the engine named is fixed, and the harness demonstrably loads the file — a file that parses is not the same as a file that applies.`
    ],
    "supply-chain/no-lockfile": [
      `A lockfile is committed, and CI installs with the frozen flag so a drifted lockfile fails the build rather than being rewritten.`
    ],
    "supply-chain/unpinned-ci-action": [
      `Every third-party action is pinned to a full commit SHA, with the version in a trailing comment.`,
      `Something keeps those SHAs current — a bot or a scheduled review — so pinning does not become stale-by-default.`
    ],
    "supply-chain/untrusted-registry": [
      `Every registry URL is HTTPS and certificate verification is enabled.`,
      `Any private certificate authority is trusted explicitly rather than by disabling the check.`
    ],
    "taint/request-reaches-execution-sink": [
      `The entry point validates the value against an allow-list — a strict pattern, a resolved host, or a fixed set — and rejects anything else, before it is passed on.`,
      `The sink no longer goes through a shell: arguments are passed as an array so no interpreter parses them.`,
      `You have checked whether the endpoint requires authentication, and said so — it changes who can reach this, not whether the chain exists.`
    ],
    "telemetry/default-pii-enabled": [
      `The setting is off, or a send hook demonstrably removes identity, cookies, and URL query strings before the event is transmitted.`,
      `You have said which data was in scope while it was on, and for how long — that determines whether this is also a disclosure to report.`
    ],
    "auth/credential-in-query-string": [
      `The credential moved to a header or a scoped cookie — or, where the protocol forces the query string, it is single-use and short-lived.`,
      `Every sink that records URLs strips it: application logs, proxy and CDN logs, **and** the telemetry SDK.`
    ],
    "context/secret-in-agent-context": [
      `**The credential has been rotated** — this file is uploaded to a model provider on every agent run, so the value must be assumed disclosed.`,
      `The instruction file now names the environment variable rather than containing its value.`
    ],
    "context/injection-in-agent-context": [
      `The instruction-override text is removed from the file.`,
      `You have checked \`git log\` for when the line was introduced and by whom, and reported it.`
    ],
    "llm/model-output-to-sink": [
      `Model output no longer flows into the sink directly.`,
      `The model now selects from a fixed set of named operations with typed parameters, and the selection is validated against that set before anything executes.`
    ],
    "llm/untrusted-input-in-prompt": [
      `Instructions and external content are in separate message roles, not concatenated into one string.`,
      `External content is wrapped in explicit delimiters, and the system prompt states that content inside them is data to analyze and never a directive to follow.`
    ],
    "llm/dynamic-tool-description": [
      `Every tool name, description, and parameter description is a static string literal.`,
      `Any dynamic state the tool needs to convey is returned in the tool's result instead of embedded in its description.`
    ],
    "web/raw-html-sink": [
      `The value renders as text, or passes through a maintained allow-list sanitizer immediately before the sink.`,
      `Sanitization happens at render time, not only at the point the data was stored.`
    ],
    "web/disabled-tls-verification": [
      `Certificate verification is enabled again.`,
      `If a self-signed certificate is genuinely needed, that specific CA is pinned for that one client rather than verification being disabled globally.`
    ],
    "context/stale-instruction-reference": [
      `The referenced path or script exists, or the line has been removed.`,
      `You spot-checked the rest of the file for other claims that no longer hold.`
    ],
    "context/stale-doc-parameter": [
      `The doc block matches the current signature exactly, or has been deleted.`
    ],
    "context/contradicted-comment": [
      `The comment describes what the code actually does now — or, if the comment described correct intent the code fails to meet, that gap is filed or fixed and noted here.`
    ],
    "context/commented-out-code": [
      `The commented-out block is deleted (git history retains it).`
    ],
    "structure/monolith-file": [
      `The file is split along a seam that already existed — a group of functions sharing state — not chopped at an arbitrary line count.`,
      `Every import site still resolves and the tests pass.`
    ],
    "structure/oversized-function": [
      `The extracted pieces have names that describe what they do, so the caller reads as a sequence of steps.`,
      `Behaviour is unchanged — verify with existing tests before and after.`
    ],
    "structure/silenced-error": [
      `The error is handled, logged with enough context to identify the call, or allowed to propagate.`,
      `If the error is genuinely expected, a comment names which error and why swallowing it is correct.`
    ]
  };

  return [...(byRule[finding.ruleId] || []), ...generic];
}
